export const categories = [
    'character',
    'shop',
    'dandelion',
    'race',
    'fast-travel',
    'scenic-ride',
    'antler',
    'apple',
    'blackberry',
    'carrot',
    'delphinium',
    'dryad-saddle-mushroom',
    'eagle-feather',
    'fossil',
    'horseshoe',
    'king-boletus-mushroom',
    'moss',
    'poppy',
    'raspberry',
    'raven-feather',
    'seagull-feather',
    'sulfur-shelf-mushroom',
    'sunflower',
    'violet',
    'water-lily',
    'weekly-quest',
    'deliveries',
    'artefacts',
] as const;

export type TCategory = (typeof categories)[number];
