export const upgradeItems: string[] = [
    'Dandelions',
    'Deer Antlers',
    'Apples',
    'Blackberries',
    'Wild Carrots',
    'Delphinium',
    "Dryad's Saddle Mushrooms",
    'Eagle Feathers',
    'Fossils',
    'Old Horseshoes',
    'King Boletus Mushrooms',
    'Moss',
    'Poppies',
    'Raspberries',
    'Raven Feathers',
    'Seagull Feathers',
    'Sulfur Shelf Mushrooms',
    'Sunflowers',
    'Violets',
    'Water Lilies',
    'Activity Tokens',
];
