import path from 'node:path';

const root = path.resolve(__dirname, '..', '..');

/** The FModel export of the game's `Content` directory (_local data_). */
export const contentDir = path.join(
    root,
    'fmodel/Output/Exports/ThunderHorse/Content'
);

/** The Fiddler Classic export of the LootLocker catalogues (_server data_). */
export const cataloguesDir = path.join(root, 'fiddler-classic/Output/Exports');

export const publicDir = path.join(root, 'public');

/** Generated by `database:import`. Do not edit by hand. */
export const itemsPath = path.join(publicDir, 'database/items.json');

/** Maintained by hand: the colours of each item. */
export const coloursPath = path.join(publicDir, 'database/colours.json');

/** Maintained by hand: listings the catalogues don't know about, like DLCs. */
export const extrasPath = path.join(publicDir, 'database/extras.json');

/** Generated by `database:import`. Every file in here is owned by the import. */
export const iconsDir = path.join(publicDir, 'icon/256/item');

/** Generated by `database:build` and consumed by the app. */
export const databasePath = path.join(root, 'app/data/database.json');
