/** A way to obtain an item, exactly as offered by the game. */
export type ImportedListing = {
    shop: string;
    faction?: string;
    level?: number;
    bundle?: string;
    cost: number;
    currency: string;
    available: boolean;
};

/** An item of `public/database/items.json`, as generated by `database:import`. */
export type ImportedItem = {
    id: string;
    name: string;
    type: string;
    statsType?: string;
    upgradeItem?: string;
    imagePath?: string;
    listings: ImportedListing[];
};

/** An entry of `public/database/extras.json`: a listing the catalogues don't know about. */
export type ExtraListing = Omit<ImportedListing, 'available'> & {
    items: string[];
};

/**
 * The content of `public/database/colours.json`: the colours of each item by
 * its ID. An empty list states that the item deliberately has no colour, a
 * list with an empty colour that its colours still need to be filled in.
 */
export type Colours = Record<string, string[]>;
